### ISSUE TITLE
Lexical query for labores produced no result

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-games#9]
double-clicking on labores from Alpheios test site got Lexical query produced no result.
lookup for labores gives a noun. verb etc.
the diagram for labors is wrong. it shows the one from previous sentence. only after displaying the diagram for nullos, I get the right one for labores

**Comment by balmas** [comment]
ah this is interesting. The source of the problem is that the data in the page which identifies the treebank word to retrieve is incorrectly formatted. This causes the request to crash when it should just gracefully go on to the regular lookup.  I will enter an issue for that. And for fixing the text itself.

**Comment by balmas** [comment]
I have fixed the references in the text in the master branch. I didn't update the the inflection games branch of the text for this yet, but they will be there when we merge that branch to master.

**Comment by monzug** [comment]
verified
